/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 59399
 */
public class EditarP extends javax.swing.JFrame {

    /**
     * Creates new form EditarP
     */
    public EditarP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/administradorr.png"))); // NOI18N

        jLabel2.setText("CONTROL ADMINISTRATIVO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("            ¿Qué deseas realizar?\n\nPara editar ,buscar y eliminar un \nproducto, búscalo por codigo unico \nusando la barra de búsqueda.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("   Codigo del producto");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/editr.png"))); // NOI18N

        jLabel5.setText("Editar o actualizacion de productos");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/eliminacionn.png"))); // NOI18N

        jLabel7.setText("Eliminar productos del sistema");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setText("Buscar Productos");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/buscaa.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(62, 62, 62))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcodigo)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        String codigoP=txtcodigo.getText().trim();
        if (codigoP.isEmpty()) {
            JOptionPane.showMessageDialog(null, "EL buscador por codigo no puede estar vacion ,intente de nuevo");
            return;
            
        }
        if (!codigoP.matches("\\d{5}")) {
            JOptionPane.showMessageDialog(null, "El codigo debe contener cinco digitos de numeros enteros positivos");
            return;
        }
        
        buscarcodigoPorcodigooP(codigoP);
        
    }//GEN-LAST:event_jLabel8MouseClicked
 private void buscarcodigoPorcodigooP(String codigoUnico) {
    File archivo = new File("DatosProductos/" + codigoUnico + ".txt");
    System.out.println("Buscando en: " + archivo.getAbsolutePath());

    if (!archivo.exists()) {
        JOptionPane.showMessageDialog(null, "El archivo del producto no existe");
        return;
    }

    try {
        // Sin especificar codificación (usa la predeterminada del sistema)
        List<String> lineas = Files.readAllLines(archivo.toPath());

        StringBuilder codigoEncontrado = new StringBuilder();
        boolean encontrado = false;
        boolean leyendo = false;

        for (String linea : lineas) {
            System.out.println("Línea: " + linea);

            // Cuidado con los acentos, asegúrate de que diga "Codigo" sin tilde
            if (linea.trim().contains("Codigo: " + codigoUnico)) {
                leyendo = true;
                encontrado = true;
            }

            if (leyendo) {
                codigoEncontrado.append(linea).append("\n");
                if (linea.contains("-----------------------------")) {
                    break;
                }
            }
        }

        if (encontrado) {
            JOptionPane.showMessageDialog(null, "Producto encontrado:\n\n" + codigoEncontrado.toString());
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ningún producto con ese código.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al leer el archivo: " + e.getMessage());
    }
}
    
  
    
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
String codi=txtcodigo.getText().trim();
        if (codi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes completar el campo de codigo del producto");
            return;
        }
        if (!codi.matches("\\d{5}")) {
            JOptionPane.showMessageDialog(null, "debe contener 5 digitos  enteros");
            return;
        }
        
        Eliminarproductos(codi); 
    }//GEN-LAST:event_jLabel7MouseClicked

    private void Eliminarproductos(String eliminar){
     File archivo = new File("DatosProductos/" + eliminar + ".txt");

    if (!archivo.exists()) {
        JOptionPane.showMessageDialog(null, "El archivo del producto no existe.");
        return;
    }

    int respuesta = JOptionPane.showConfirmDialog(
            null,
            "¿Estás seguro que deseas eliminar el archivo del cliente?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
    );

    if (respuesta == JOptionPane.YES_OPTION) {
        if (archivo.delete()) {
            JOptionPane.showMessageDialog(null, "Archivo eliminado correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el archivo.");
        }
    }
    
    }

    
    
    
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
String editar= txtcodigo.getText().trim();

        if (editar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No puedes dejar en blanco");
            return;
        }
        
        if (!editar.matches("\\d{5}")) {
            JOptionPane.showMessageDialog(null, "Debe contener 5 digitos enteros");
            return;
        }
        
        EditarProductos(editar);
        
    }//GEN-LAST:event_jLabel5MouseClicked
   private void EditarProductos(String editt) {
    File archivo = new File("DatosProductos/" + editt + ".txt");

    if (!archivo.exists()) {
        JOptionPane.showMessageDialog(null, "El archivo del producto no existe.");
        return;
    }

    try {
        // Leer todas las líneas del archivo
        List<String> lineas = Files.readAllLines(archivo.toPath());

        // Pedir los nuevos valores
        String nuevoPrecio = JOptionPane.showInputDialog("Ingrese el nuevo precio:");
        if (nuevoPrecio == null) {
            JOptionPane.showMessageDialog(null, "Edición cancelada. No se realizaron cambios.");
            return;
        }

        String nuevoStock = JOptionPane.showInputDialog("Ingrese el nuevo stock:");
        if (nuevoStock == null) {
            JOptionPane.showMessageDialog(null, "Edición cancelada. No se realizaron cambios.");
            return;
        }

        boolean actualizoPrecio = false;
        boolean actualizoStock = false;
        boolean encontroLineaActualizacion = false;

        // Reemplazar datos y buscar si ya existe la línea de actualización
        for (int i = 0; i < lineas.size(); i++) {
            if (lineas.get(i).startsWith("Precio:")) {
                lineas.set(i, "Precio: " + nuevoPrecio);
                actualizoPrecio = true;
            } else if (lineas.get(i).startsWith("Stock:")) {
                lineas.set(i, "Stock: " + nuevoStock);
                actualizoStock = true;
            } else if (lineas.get(i).startsWith("Última actualización:")) {
                encontroLineaActualizacion = true;
                // Actualizar la línea con nueva fecha
                String fecha = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
                lineas.set(i, "Última actualización: " + fecha);
            }
        }

        // Si no existía línea de actualización, agregarla al final
        if (!encontroLineaActualizacion) {
            String fecha = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
            lineas.add("Última actualización: " + fecha);
        }

        // Escribir de nuevo el archivo
        Files.write(archivo.toPath(), lineas, StandardOpenOption.TRUNCATE_EXISTING);

        if (actualizoPrecio || actualizoStock) {
            JOptionPane.showMessageDialog(null, "Producto actualizado correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron los campos Precio o Stock para actualizar.");
        }

    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Error al editar el producto: " + e.getMessage());
    }
}
        
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtcodigo;
    // End of variables declaration//GEN-END:variables
}
